services:
  app:
    image: ghcr.io/ikapiar/tawasul:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "80:3000"
    env_file:
      - ./.env.docker-compose
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - "./packages/backend/drizzle:/docker-entrypoint-initdb.d"
      - "./packages/backend/seed/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql"
    ports:
      - "5432:5432"
