services:
  backend:
    image: ghcr.io/tawasul/backend:${VERSION:-latest}
    pull_policy: always
    build:
      context: packages/backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker-compose
  frontend:
    image: ghcr.io/tawasul/frontend:${VERSION:-latest}
    pull_policy: always
    build:
      context: packages/frontend
      args:
        - BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://localhost:3000/}
    depends_on:
      - backend
    ports:
      - "80:80"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - "./packages/backend/drizzle:/docker-entrypoint-initdb.d"
      - "./packages/backend/seed/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql"
    ports:
      - "5432:5432"
