services:
  backend:
    build: packages/backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker-compose
  frontend:
    build: packages/frontend
    depends_on:
      - backend
    ports:
      - "80:80"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - "./packages/backend/drizzle:/docker-entrypoint-initdb.d"
      - "./packages/backend/seed/seeder.sql:/docker-entrypoint-initdb.d/seeder.sql"
    ports:
      - "5432:5432"
