apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tawasul
  namespace: tawasul-dev
spec:
  ingressClassName: nginx
  rules:
    - host: tawasul.tawasul-dev.svc.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tawasul
                port:
                  number: 3000
