apiVersion: v1
kind: Service
metadata:
  name: tawasul
  labels:
    app: tawasul
  namespace: tawasul-dev
spec:
  selector:
    app: tawasul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000